[package]
name = "cr_cpu_common"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# TODO: use cargo insta for something here, it looks fun!

[dev-dependencies]
insta = "1.34.0"