[package]
name = "cr_cpu_emu"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cr_cpu_common = { path = "../cr_cpu_common" }